kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: service-reader
rules:
- apiGroups: [""] 
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
