apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: simulation-to-log-with-replace-field
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: simulation-source
    properties:
      message: '{ "foo":"John", "bar":30, "baz":"ciao" }'
      contentType: 'application/json'
  steps:
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: replace-field-action
    properties:
      enabled: "foo,bar"
      disabled: "baz"
      renames: "foo:fii2"
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
