apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: aws-kinesis-to-log
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: aws-kinesis-source
    properties:
      accessKey: 'AKIA3LNAP5JENC3R64DG'
      secretKey: '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'
      region: 'eu-west-1'
      stream: streamTest 
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
