apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: bitcoin-to-log
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: bitcoin-source
    properties:
      period: 12000
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
