apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: namespace-to-log
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kubernetes-pods-source
    properties:
      masterUrl: 'https://192.168.99.100:8443'
      token: '<token>'
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
