apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: bitcoin-to-s3
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: bitcoin-source
    properties:
      period: 10000
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: aws-s3-sink
    properties:
      bucketNameOrArn: bucketName
      accessKey: access
      secretKey: secret
      region: region
