apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: simulation-to-sqlserver
spec:
  integration:
    dependencies:
    - "mvn:com.microsoft.sqlserver:mssql-jdbc:9.2.1.jre11"
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
    properties:
      period: "5000"
      message: '{ "user_id":"3", "username":"Malpensa", "city":"Roma" } '
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: sqlserver-sink
    properties:
      serverName: 172.17.0.5
      username: sa
      password: Password!
      query: 'INSERT INTO master.dbo.accounts (user_id,username,city) VALUES (:#user_id,:#username,:#city)'
      port: 1433
      databaseName: test
