apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: s3-to-kafka
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: aws-s3-source
    properties:
      bucketNameOrArn: 'bitcoin-kafka-connector'
      accessKey: 'access'
      secretKey: 'secrets'
      region: 'reg'
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-not-secured-sink
    properties:
      brokers: 'my-cluster-kafka-bootstrap:9092'
      topic: 'test-topic'
