apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: time-ec2-log
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
    properties:
      message: '"oscerd"'
  steps:
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: insert-header-action
    properties:
      name: "instanceIds"
      value: "i-05f72333bf81bbb89"
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: aws-ec2-sink
    properties:
      accessKey: 'access'
      secretKey: 'secret'
      region: 'region'
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
