apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: kafka-to-log-28
spec:
  integration:
    configuration:
      - type: property
        value: "quarkus.log.level=DEBUG"
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-not-secured-source
    properties:
      brokers: 'my-cluster-kafka-bootstrap:9092'
      topic: 'test-topic-1'
      autoCommitEnable: false
      allowManualCommit: true
  steps:
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: telegram-sink
    properties:
      authorizationToken: "<auth_toke>"
      chatId: "<chat_id>"
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-manual-commit-action
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
