apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: s3-to-kafka-with-timestamp-router-1
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: aws-s3-source
    properties:
      bucketNameOrArn: 'camel-kafka-connector'
      accessKey: 'accessKey'
      secretKey: 'secretKey'
      region: 'region'
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
