apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: flow-binding
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: simulation-source
    properties:
      message: 'SQS Message'
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: aws-sqs-fifo-sink
    properties:
      queueNameOrArn: "camel-kamelet.fifo"
      accessKey: "xxxx"
      secretKey: "yyyy"
      region: "region"
      messageGroupIdStrategy: "useExchangeId"
      messageDeduplicationIdStrategy: "useExchangeId"
