apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: ddb-streams-to-telegram
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: aws-ddb-streams-source
    properties:
      accessKey: xxxx
      secretKey: yyyy
      region: test
      table: test 
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: telegram-sink
    properties:
      authorizationToken: "authToken"
      chatId: "chatId"
